//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeSchedule
    {
        public long ChangeScheduleID { get; set; }
        public Nullable<long> ScheduleID { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<long> MemberID { get; set; }
        public Nullable<bool> IsPermanent { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> MemberType { get; set; }
        public Nullable<long> GroupTypeID { get; set; }
    }
}
