//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeDiscipline
    {
        public long CodeDisciplineID { get; set; }
        public string Name { get; set; }
        public Nullable<int> SectionNumber { get; set; }
        public Nullable<int> RevisionNumber { get; set; }
        public Nullable<System.DateTime> EffectivityDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
