//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyPayrollInfo
    {
        public long CompanyPayrollInfoID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public Nullable<int> SemiFirstCutoff { get; set; }
        public Nullable<int> SemiSecondCutoff { get; set; }
        public Nullable<int> MonthlyCutoffDate { get; set; }
        public Nullable<int> WeeklyCutoffDay { get; set; }
        public string SSS { get; set; }
        public string Philhealth { get; set; }
        public string TIN { get; set; }
        public Nullable<long> PayrollBankID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public byte[] Picture { get; set; }
        public string ContactNumber { get; set; }
        public string HDMF { get; set; }
        public string SSSBranchCode { get; set; }
        public string PhilHealthBranchCode { get; set; }
        public string HDMFBranchCode { get; set; }
        public Nullable<int> PayrollCodeID { get; set; }
        public byte[] WaterMark { get; set; }
        public byte[] Footer { get; set; }
    }
}
