//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceCommand
    {
        public long DeviceCommandID { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> CommandType { get; set; }
        public string Data { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<System.DateTime> ChangeStatusDate { get; set; }
        public Nullable<int> NumberOfTries { get; set; }
    }
}
