//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisciplineOffens
    {
        public long DisciplineOffensesID { get; set; }
        public Nullable<long> CodeDisciplineID { get; set; }
        public Nullable<int> ReferenceNumber { get; set; }
        public string Offenses { get; set; }
        public string Penalty { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
