//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTRCorrection
    {
        public long DTRCorrectionID { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<long> RequestedBy { get; set; }
        public Nullable<System.DateTime> DTRDate { get; set; }
        public Nullable<System.DateTime> DTRTime { get; set; }
        public Nullable<int> LoginType { get; set; }
        public string RequestRemarks { get; set; }
        public Nullable<long> ChangeStatusBy { get; set; }
        public string ChangeStatusRemarks { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> ChangeStatusDate { get; set; }
    }
}
