//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class E201_Eligibilities
    {
        public long E201EligibilityID { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public string ExamName { get; set; }
        public string ExamDate { get; set; }
        public string Rating { get; set; }
        public string ExamPlace { get; set; }
    }
}
