//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class E201_Trainings
    {
        public long E201TrainingID { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public string TrainingName { get; set; }
        public string TrainingDate { get; set; }
        public string Provider { get; set; }
        public string Venue { get; set; }
        public string Instructor { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public string Remarks { get; set; }
    }
}
