//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class E201_Identification
    {
        public long E201IdentificationID { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public Nullable<int> IdentificationType { get; set; }
        public string IDNumber { get; set; }
        public string DateIssued { get; set; }
        public string DateExpired { get; set; }
        public string PlaceIssued { get; set; }
    }
}
