//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class E201_DisciplinaryAction
    {
        public long DisciplinaryActionID { get; set; }
        public Nullable<int> DisciplinaryType { get; set; }
        public Nullable<long> CodeDisciplineID { get; set; }
        public Nullable<long> DisciplineOffensesID { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string ActionTaken { get; set; }
        public string CiteReason { get; set; }
        public string EffectivityDate { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public Nullable<long> DisciplinePenaltyID { get; set; }
        public string Level { get; set; }
        public string Notes { get; set; }
    }
}
