//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class E201_JobExperiences
    {
        public long E201JobExperienceID { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public string CompanyName { get; set; }
        public string Position { get; set; }
        public string NatureOfWork { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public string Supervisor { get; set; }
        public string SupervisorPosition { get; set; }
        public string ReasonForLeaving { get; set; }
    }
}
