//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class E201_PersonalAction
    {
        public long PersonalActionID { get; set; }
        public string PersonalActionTypeID { get; set; }
        public Nullable<decimal> SalaryFrom { get; set; }
        public Nullable<decimal> SalaryTo { get; set; }
        public string LocationFrom { get; set; }
        public string LocationTo { get; set; }
        public Nullable<decimal> EColaFrom { get; set; }
        public Nullable<decimal> EColaTo { get; set; }
        public string LevelFrom { get; set; }
        public string LevelTo { get; set; }
        public string PositionFrom { get; set; }
        public string PositionTo { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> EffectivityDate { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public string Notes { get; set; }
    }
}
