//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class E201_ContactInformation
    {
        public long E201ContactInformationID { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public string HomePhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string WorkPhoneNumber { get; set; }
        public string PersonalEmail { get; set; }
        public string FacebookAccount { get; set; }
        public string LinkedInAccount { get; set; }
        public string TwitterAccount { get; set; }
    }
}
