//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class E201_Documents
    {
        public int E201DocumentID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Filename { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string FileExtension { get; set; }
        public string FileSize { get; set; }
        public byte[] FileStream { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> ReferenceID { get; set; }
        public Nullable<int> ReferenceType { get; set; }
        public Nullable<int> Category { get; set; }
    }
}
