//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTransaction
    {
        public long EmployeeTransactionID { get; set; }
        public Nullable<long> MemberID { get; set; }
        public Nullable<int> MemberType { get; set; }
        public Nullable<long> PayrollTransactionTypeID { get; set; }
        public Nullable<int> Cutoff { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string AdditionalInfo { get; set; }
        public Nullable<long> ReferenceID { get; set; }
        public long SubTypeID { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<int> StartMonth { get; set; }
        public Nullable<int> EndMonth { get; set; }
        public Nullable<int> StartYear { get; set; }
        public Nullable<int> EndYear { get; set; }
        public Nullable<int> AmountType { get; set; }
    }
}
