//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class GovCertification
    {
        public long GovCertificationID { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public Nullable<int> MonthStart { get; set; }
        public Nullable<int> YearStart { get; set; }
        public Nullable<int> MonthEnd { get; set; }
        public Nullable<int> YearEnd { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
