//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class GovCertificationDetail
    {
        public long GovCertificationDetailID { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> SSS { get; set; }
        public Nullable<decimal> EC { get; set; }
        public Nullable<decimal> PhilEE { get; set; }
        public Nullable<decimal> PhilER { get; set; }
        public Nullable<long> GovCertificationSettingID { get; set; }
        public Nullable<long> GovCertificationID { get; set; }
    }
}
