//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class GovCertificationSetting
    {
        public long GovCertificationSettingID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public string ReceiptNo { get; set; }
        public string CollectingBank { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
