//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public long GroupID { get; set; }
        public string GroupName { get; set; }
        public Nullable<long> GroupTypeID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string GroupCode { get; set; }
        public Nullable<bool> IsEditable { get; set; }
        public Nullable<long> ParentGroupID { get; set; }
        public Nullable<long> ParentGroupTypeID { get; set; }
    }
}
