//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMember
    {
        public long GroupMemberID { get; set; }
        public Nullable<long> GroupID { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public Nullable<System.DateTime> DateApplicable { get; set; }
        public Nullable<long> GroupTypeID { get; set; }
    }
}
