//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupType
    {
        public long GroupTypeID { get; set; }
        public string GroupTypeName { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsMultiple { get; set; }
        public string GroupTypeCode { get; set; }
        public Nullable<bool> IsEditable { get; set; }
        public string ClassObject { get; set; }
        public string Library { get; set; }
    }
}
