//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayMember
    {
        public long HolidayMemberID { get; set; }
        public Nullable<long> HolidayID { get; set; }
        public Nullable<long> EmployeeID { get; set; }
    }
}
