//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public long HolidayID { get; set; }
        public string HolidayName { get; set; }
        public Nullable<System.DateTime> HolidayDate { get; set; }
        public int HolidayType { get; set; }
        public bool IsUniversal { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> HolidayTime { get; set; }
        public Nullable<int> MinutesHoliday { get; set; }
    }
}
