//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveProfileDetail
    {
        public long LeaveProfileDetailID { get; set; }
        public Nullable<long> LeaveProfileID { get; set; }
        public Nullable<long> LeaveTypeID { get; set; }
        public Nullable<bool> IsAccrued { get; set; }
        public Nullable<decimal> LeaveGrants { get; set; }
        public Nullable<decimal> CarryOver { get; set; }
        public Nullable<decimal> ConvertibleToCash { get; set; }
        public Nullable<decimal> Taxable { get; set; }
        public string AccrualDetailString { get; set; }
    }
}
