//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveProfile
    {
        public long LeaveProfileID { get; set; }
        public string Description { get; set; }
        public Nullable<int> ResetMonth { get; set; }
        public Nullable<int> ResetDay { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> MinimumTenureMonth { get; set; }
    }
}
