//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TA3DBContext : DbContext
    {
        public TA3DBContext()
            : base("name=TA3DBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Announcement> Announcements { get; set; }
        public virtual DbSet<ChangeRestday> ChangeRestdays { get; set; }
        public virtual DbSet<ChangeSchedule> ChangeSchedules { get; set; }
        public virtual DbSet<CodeDiscipline> CodeDisciplines { get; set; }
        public virtual DbSet<CompanyPayrollInfo> CompanyPayrollInfoes { get; set; }
        public virtual DbSet<DisciplineOffens> DisciplineOffenses { get; set; }
        public virtual DbSet<DisciplinePenalty> DisciplinePenalties { get; set; }
        public virtual DbSet<DTRCorrection> DTRCorrections { get; set; }
        public virtual DbSet<E201_Addresses> E201_Addresses { get; set; }
        public virtual DbSet<E201_BenefitTypes> E201_BenefitTypes { get; set; }
        public virtual DbSet<E201_ContactInformation> E201_ContactInformation { get; set; }
        public virtual DbSet<E201_DisciplinaryAction> E201_DisciplinaryAction { get; set; }
        public virtual DbSet<E201_EducationalBackground> E201_EducationalBackground { get; set; }
        public virtual DbSet<E201_Eligibilities> E201_Eligibilities { get; set; }
        public virtual DbSet<E201_EmployeeBenefits> E201_EmployeeBenefits { get; set; }
        public virtual DbSet<E201_EmployeeBenefitTypes> E201_EmployeeBenefitTypes { get; set; }
        public virtual DbSet<E201_Families> E201_Families { get; set; }
        public virtual DbSet<E201_Identification> E201_Identification { get; set; }
        public virtual DbSet<E201_JobExperiences> E201_JobExperiences { get; set; }
        public virtual DbSet<E201_PersonalAction> E201_PersonalAction { get; set; }
        public virtual DbSet<E201_PersonalActionTypes> E201_PersonalActionTypes { get; set; }
        public virtual DbSet<E201_PersonalInfo> E201_PersonalInfo { get; set; }
        public virtual DbSet<E201_Trainings> E201_Trainings { get; set; }
        public virtual DbSet<EmployeeCustomInfo> EmployeeCustomInfoes { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeTransaction> EmployeeTransactions { get; set; }
        public virtual DbSet<GovCertification> GovCertifications { get; set; }
        public virtual DbSet<GovCertificationDetail> GovCertificationDetails { get; set; }
        public virtual DbSet<GovCertificationSetting> GovCertificationSettings { get; set; }
        public virtual DbSet<GroupMember> GroupMembers { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<GroupType> GroupTypes { get; set; }
        public virtual DbSet<HolidayMember> HolidayMembers { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<LeaveCredit> LeaveCredits { get; set; }
        public virtual DbSet<LeaveDeduction> LeaveDeductions { get; set; }
        public virtual DbSet<LeaveProfileDetail> LeaveProfileDetails { get; set; }
        public virtual DbSet<LeaveProfile> LeaveProfiles { get; set; }
        public virtual DbSet<Leaf> Leaves { get; set; }
        public virtual DbSet<LeaveType> LeaveTypes { get; set; }
        public virtual DbSet<OfficialBusiness> OfficialBusinesses { get; set; }
        public virtual DbSet<Outbox> Outboxes { get; set; }
        public virtual DbSet<Overtime> Overtimes { get; set; }
        public virtual DbSet<Payroll> Payrolls { get; set; }
        public virtual DbSet<Payroll13thMonthCutOff> Payroll13thMonthCutOff { get; set; }
        public virtual DbSet<PayrollAdjustment> PayrollAdjustments { get; set; }
        public virtual DbSet<PayrollBank> PayrollBanks { get; set; }
        public virtual DbSet<PayrollEntry> PayrollEntries { get; set; }
        public virtual DbSet<PayrollInfo> PayrollInfoes { get; set; }
        public virtual DbSet<PayrollJournalVoucher> PayrollJournalVouchers { get; set; }
        public virtual DbSet<PayrollLoan> PayrollLoans { get; set; }
        public virtual DbSet<PayrollProfile> PayrollProfiles { get; set; }
        public virtual DbSet<PayrollRate> PayrollRates { get; set; }
        public virtual DbSet<PayrollTransactionType> PayrollTransactionTypes { get; set; }
        public virtual DbSet<PreviousPayrollEntry> PreviousPayrollEntries { get; set; }
        public virtual DbSet<RestdayLeaf> RestdayLeaves { get; set; }
        public virtual DbSet<SalaryLevel> SalaryLevels { get; set; }
        public virtual DbSet<SavedSession> SavedSessions { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<SingleDaySchedule> SingleDaySchedules { get; set; }
        public virtual DbSet<Subordinate> Subordinates { get; set; }
        public virtual DbSet<TimeLog> TimeLogs { get; set; }
        public virtual DbSet<UserRight> UserRights { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<ZKDevice> ZKDevices { get; set; }
        public virtual DbSet<ZKUserInfo> ZKUserInfoes { get; set; }
        public virtual DbSet<CustomTransactionType> CustomTransactionTypes { get; set; }
        public virtual DbSet<DeviceCommand> DeviceCommands { get; set; }
        public virtual DbSet<E201_Documents> E201_Documents { get; set; }
        public virtual DbSet<PagibigBracket> PagibigBrackets { get; set; }
        public virtual DbSet<PayrollAllowanceType> PayrollAllowanceTypes { get; set; }
        public virtual DbSet<PayrollCodeDetail> PayrollCodeDetails { get; set; }
        public virtual DbSet<PayrollCode> PayrollCodes { get; set; }
        public virtual DbSet<PayrollCommission> PayrollCommissions { get; set; }
        public virtual DbSet<PayrollLoanType> PayrollLoanTypes { get; set; }
        public virtual DbSet<PayrollRateProfile> PayrollRateProfiles { get; set; }
        public virtual DbSet<PhilHealthBracket> PhilHealthBrackets { get; set; }
        public virtual DbSet<PieceRateMultiplier> PieceRateMultipliers { get; set; }
        public virtual DbSet<PieceRate> PieceRates { get; set; }
        public virtual DbSet<PieceWork> PieceWorks { get; set; }
        public virtual DbSet<PreviousEmploymentInfo> PreviousEmploymentInfoes { get; set; }
        public virtual DbSet<SeniorityBracket> SeniorityBrackets { get; set; }
        public virtual DbSet<SSSBracket> SSSBrackets { get; set; }
        public virtual DbSet<TaxBracket> TaxBrackets { get; set; }
        public virtual DbSet<TaxBracketType> TaxBracketTypes { get; set; }
    }
}
