//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outbox
    {
        public long OutboxID { get; set; }
        public string FromEmail { get; set; }
        public string ToEmail { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public int NumberOfTries { get; set; }
        public Nullable<bool> UseHTML { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
    }
}
