//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Overtime
    {
        public long OvertimeID { get; set; }
        public Nullable<System.DateTime> OTDate { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<long> RequestedBy { get; set; }
        public string RequestRemarks { get; set; }
        public Nullable<System.DateTime> TimeStart { get; set; }
        public Nullable<int> MinutesOT { get; set; }
        public Nullable<int> MinutesBreak { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<long> ChangeStatusBy { get; set; }
        public Nullable<System.DateTime> ChangeStatusDate { get; set; }
        public string ChangeStatusRemarks { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public Nullable<int> ApprovedOT { get; set; }
        public Nullable<int> ApprovedBreak { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
    }
}
