//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollEntry
    {
        public long PayrollEntryID { get; set; }
        public Nullable<long> PayrollID { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public Nullable<long> PayrollTransactionTypeID { get; set; }
        public decimal Count { get; set; }
        public decimal Amount { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Cutoff { get; set; }
        public long SubTypeID { get; set; }
        public Nullable<long> ReferenceID { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public string OtherInfo { get; set; }
    }
}
