//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollAllowanceType
    {
        public long PayrollAllowanceTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public Nullable<bool> IsEditable { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
