//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        public long PayrollID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Cutoff { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> PayrollFrequency { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> ReferenceType { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Divisor { get; set; }
        public Nullable<decimal> MonthMultiplier { get; set; }
        public Nullable<int> Prev13thOperator { get; set; }
        public Nullable<decimal> MonthDivisor { get; set; }
    }
}
