//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollLoan
    {
        public long PayrollLoanID { get; set; }
        public Nullable<long> PayrollLoanTypeID { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Cutoff { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> InterestPercentage { get; set; }
        public Nullable<decimal> PrincipalAmount { get; set; }
        public Nullable<short> PayableType { get; set; }
    }
}
