//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollRate
    {
        public long PayrollRateID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> PayrollRateProfileID { get; set; }
    }
}
