//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollBank
    {
        public long PayrollBankID { get; set; }
        public string BankCode { get; set; }
        public string BankAddress { get; set; }
        public string BankName { get; set; }
        public string AccountNumber { get; set; }
        public string ContactPerson { get; set; }
        public string Signatory1 { get; set; }
        public string Signatory2 { get; set; }
        public string Signatory3 { get; set; }
        public string Signatory4 { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string BranchCode { get; set; }
    }
}
