//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollCodeDetail
    {
        public int PayrollCodeDetailID { get; set; }
        public int PayrollCodeID { get; set; }
        public int TransactionCodeID { get; set; }
        public string Codes { get; set; }
        public short JournalEntryType { get; set; }
        public Nullable<long> TransactionCodeSubID { get; set; }
    }
}
