//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollProfile
    {
        public long PayrollProfileID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> PayrollFrequency { get; set; }
        public Nullable<decimal> WorkingDays { get; set; }
        public Nullable<decimal> MinimumWage { get; set; }
        public Nullable<decimal> ECOLA { get; set; }
        public Nullable<decimal> HoursPerDay { get; set; }
        public Nullable<bool> NoWorkNoPayOnAHoliday { get; set; }
        public Nullable<bool> NoWorkNoPayOnASpecialHoliday { get; set; }
        public string PayslipNote { get; set; }
    }
}
