//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll13thMonthCutOff
    {
        public long Payroll13thMonthCutOffID { get; set; }
        public long CompanyPayrollInfoID { get; set; }
        public int Release { get; set; }
        public int MonthFrom { get; set; }
        public int MonthFromCutOff { get; set; }
        public int MonthTo { get; set; }
        public int MonthToCutOff { get; set; }
    }
}
