//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollInfo
    {
        public long PayrollInfoID { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public Nullable<long> PayrollProfileID { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<decimal> SalaryAmount { get; set; }
        public Nullable<int> SalaryType { get; set; }
        public Nullable<long> TaxCodeID { get; set; }
        public string AccountNo { get; set; }
        public Nullable<long> PayrollBankID { get; set; }
        public Nullable<int> TaxType { get; set; }
        public Nullable<decimal> TaxValue { get; set; }
        public Nullable<int> SSSType { get; set; }
        public Nullable<decimal> SSSValue { get; set; }
        public Nullable<int> PHILType { get; set; }
        public Nullable<decimal> PHILValue { get; set; }
        public Nullable<int> HDMFType { get; set; }
        public Nullable<decimal> HDMFValue { get; set; }
        public Nullable<bool> YearlyBasedTax { get; set; }
        public Nullable<int> AccountType { get; set; }
        public Nullable<int> PayrollRateProfileID { get; set; }
        public string CommissionAccountNo { get; set; }
        public Nullable<long> CommissionPayrollBankID { get; set; }
        public Nullable<int> CommissionAccountType { get; set; }
        public long SalaryLevelID { get; set; }
    }
}
