//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PieceWork
    {
        public long PieceWorkID { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public Nullable<long> PieceRateID { get; set; }
        public Nullable<long> PieceRateMultiplierID { get; set; }
        public Nullable<decimal> RatePerUnit { get; set; }
        public Nullable<decimal> Multiplier { get; set; }
        public Nullable<decimal> UnitCount { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
    }
}
