//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PieceRate
    {
        public long PieceRateID { get; set; }
        public string PieceRateCode { get; set; }
        public string Description { get; set; }
        public string UnitOfMeasurement { get; set; }
        public Nullable<decimal> RatePerUnit { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
