//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreviousPayrollEntry
    {
        public int PreviousPayrollEntryID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> YearApplicable { get; set; }
        public Nullable<decimal> TaxWithheld { get; set; }
        public Nullable<decimal> DeMinimisBenefits { get; set; }
        public Nullable<decimal> GovernmentContrib { get; set; }
        public Nullable<decimal> OtherNonTaxableBenefits { get; set; }
        public Nullable<decimal> OtherNonTaxableCompensation { get; set; }
        public Nullable<decimal> TotalNonTaxable { get; set; }
        public Nullable<decimal> BasicPay { get; set; }
        public Nullable<decimal> OtherTaxableBenefits { get; set; }
        public Nullable<decimal> OtherTaxableCompensation { get; set; }
        public Nullable<decimal> TotalTaxable { get; set; }
    }
}
