//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public long ScheduleID { get; set; }
        public string ScheduleName { get; set; }
        public Nullable<short> GracePeriod { get; set; }
        public Nullable<short> MinimumOT { get; set; }
        public Nullable<short> OTRoundDown { get; set; }
        public Nullable<int> AllowEarlyInMinutes { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<short> OverbreakAction { get; set; }
        public string NightDiffString { get; set; }
        public bool MustCompleteBeforeOT { get; set; }
        public Nullable<int> ScheduleNo { get; set; }
        public bool IncludeGraceOnLate { get; set; }
        public bool MustBePresentBeforeHoliday { get; set; }
        public Nullable<short> ScheduleType { get; set; }
        public Nullable<int> UndertimeHalfdayTolerance { get; set; }
        public Nullable<int> UndertimeAbsentTolerance { get; set; }
        public Nullable<int> UndertimeRoundUp { get; set; }
        public string LateRoundUpString { get; set; }
        public Nullable<int> MinimumGapBetweenShifts { get; set; }
        public Nullable<int> OTStart { get; set; }
        public Nullable<int> MaxOT { get; set; }
        public Nullable<int> FlexiTolerance { get; set; }
        public Nullable<int> MinutesPerDay { get; set; }
        public string DetailString { get; set; }
        public Nullable<bool> NonPunching { get; set; }
        public Nullable<bool> AlwaysAllowOvertime { get; set; }
        public Nullable<bool> AutoAssignTimeLogs { get; set; }
        public Nullable<bool> ConsiderScheduleOnHoliday { get; set; }
    }
}
