//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public long SettingID { get; set; }
        public string SettingsKey { get; set; }
        public Nullable<int> ValueType { get; set; }
        public Nullable<bool> IsEncrypted { get; set; }
        public string SettingsValue { get; set; }
        public byte[] ImageValue { get; set; }
    }
}
