//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSSBracket
    {
        public long SSSBracketID { get; set; }
        public Nullable<decimal> Range { get; set; }
        public Nullable<decimal> EE { get; set; }
        public Nullable<decimal> ER { get; set; }
        public Nullable<decimal> EC { get; set; }
    }
}
