//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxBracketType
    {
        public long TaxBracketTypeID { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> Exemption { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<int> TaxTableType { get; set; }
    }
}
