//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeLog
    {
        public long TimeLogID { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<System.DateTime> RecordTime { get; set; }
        public Nullable<short> Type { get; set; }
        public Nullable<int> Checksum { get; set; }
        public string Reference { get; set; }
        public Nullable<short> ReferenceType { get; set; }
        public Nullable<System.DateTime> ActualTime { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<short> LoginMode { get; set; }
        public string Remarks { get; set; }
        public Nullable<short> ActualType { get; set; }
        public Nullable<long> TerminalID { get; set; }
        public string RawType { get; set; }
        public Nullable<int> DeviceLogID { get; set; }
        public Nullable<int> MIFAREID { get; set; }
        public string WorkCode { get; set; }
        public Nullable<System.DateTime> ActualRecordDate { get; set; }
    }
}
