//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRight
    {
        public long UserRightsID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<long> UserRoleID { get; set; }
        public string TaskValue { get; set; }
        public Nullable<short> TaskValueType { get; set; }
    }
}
