//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZKDevice
    {
        public long ZKDeviceID { get; set; }
        public string TerminalName { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> Keycode { get; set; }
        public Nullable<short> ComType { get; set; }
        public string ComValue { get; set; }
        public Nullable<short> TerminalFunction { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> ComKey { get; set; }
        public Nullable<short> DeviceType { get; set; }
        public Nullable<int> PortNumber { get; set; }
        public Nullable<short> DownloadMode { get; set; }
        public Nullable<int> DownloadInterval { get; set; }
        public Nullable<System.DateTime> DownloadTime { get; set; }
        public Nullable<System.DateTime> NextDownload { get; set; }
        public string TerminalCode { get; set; }
        public string AttLogStamp { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string InOutModeMap { get; set; }
        public string VerifyModeMap { get; set; }
        public string PushVersion { get; set; }
        public string TimeZone { get; set; }
    }
}
