//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivicExamProcedures.ExternalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZKUserInfo
    {
        public long ZKUserInfoID { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public string AccessNumber { get; set; }
        public Nullable<int> DevicePrivilege { get; set; }
        public string Password { get; set; }
        public Nullable<int> Threshold { get; set; }
        public Nullable<int> LoginMode { get; set; }
        public string RFID { get; set; }
        public string MIFAREID { get; set; }
        public string FingerprintDetails { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public byte[] Picture { get; set; }
        public string FaceTemplateData { get; set; }
        public Nullable<int> FaceTemplateLength { get; set; }
    }
}
